version: 2
updates:
  - package-ecosystem: "maven" # Indicates you're using Maven
    directory: "/" # Location of the Maven POM file
    schedule:
      interval: "weekly" # Frequency of update checks
    open-pull-requests-limit: 5 # Limit on open PRs
